"""empty message

Revision ID: a0ef45fc84b7
Revises: e95aba53a24f
Create Date: 2022-08-17 17:05:57.519146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0ef45fc84b7'
down_revision = 'e95aba53a24f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etudiants', sa.Column('email', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('etudiants', 'email')
    # ### end Alembic commands ###
